<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Neeru" failures="1" tests="4" name="my_profile.add_wallet_points" time="28.559" errors="0" timestamp="2024-04-19T01:00:38 IST" skipped="0">
  <testcase classname="my_profile.add_wallet_points" name="verify_hardcoded_amount_available" time="4.493"/>
  <system-out/>
  <testcase classname="my_profile.add_wallet_points" name="wallet_balance_verification" time="5.074"/>
  <system-out/>
  <testcase classname="my_profile.add_wallet_points" name="error_amount_verification" time="11.307"/>
  <system-out>
    <![CDATA[amount blank verifed
amount 1 verifed
amount 30000 verifed]]>
  </system-out>
  <testcase classname="my_profile.add_wallet_points" name="error_rajorpay_verification" time="7.685">
    <failure message="The following asserts failed:
	Alert message is mismatched by cancelling rajor pay payment  expected [Are you sure, you want to close the for?] but found [Are you sure, you want to close the form?]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Alert message is mismatched by cancelling rajor pay payment  expected [Are you sure, you want to close the for?] but found [Are you sure, you want to close the form?]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at my_profile.add_wallet_points.error_rajorpay_verification(add_wallet_points.java:193)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- error_rajorpay_verification -->
  <system-out>
    <![CDATA[<font color="red">Test Case Failed: error_rajorpay_verification</font>
<font color="red">Error Message: The following asserts failed:
Alert message is mismatched by cancelling rajor pay payment  expected [Are you sure, you want to close the for?] but found [Are you sure, you want to close the form?]</font>]]>
  </system-out>
</testsuite> <!-- my_profile.add_wallet_points -->
